export const logosListSerieA: any = {
  logoSerieA: 'https://media.api-sports.io/football/leagues/135.png',
  atalanta: '../../../assets/logos/serieA/atalanta.png',
  bologna: '../../../assets/logos/serieA/bologna.png',
  cagliari: '../../../assets/logos/serieA/cagliari.png',
  empoli: '../../../assets/logos/serieA/empoli.png',
  fiorentina: '../../../assets/logos/serieA/fiorentina.png',
  frosinone: '../../../assets/logos/serieA/frosinone.png',
  genoa: '../../../assets/logos/serieA/genoa.png',
  inter: '../../../assets/logos/serieA/inter.png',
  juventus: '../../../assets/logos/serieA/juventus.png',
  lazio: '../../../assets/logos/serieA/lazio.png',
  lecce: '../../../assets/logos/serieA/lecce.png',
  milan: '../../../assets/logos/serieA/milan.png',
  monza: '../../../assets/logos/serieA/monza.png',
  napoli: '../../../assets/logos/serieA/napoli.png',
  roma: '../../../assets/logos/serieA/roma.png',
  salernitana: '../../../assets/logos/serieA/salernitana.png',
  sassuolo: '../../../assets/logos/serieA/sassuolo.png',
  torino: '../../../assets/logos/serieA/torino.png',
  udinese: '../../../assets/logos/serieA/udinese.png',
  verona: '../../../assets/logos/serieA/verona.png',
};

export const logosListSerieB: any = {
  logoSerieB: 'https://media.api-sports.io/football/leagues/136.png',
  ascoli: '../../../assets/logos/serieB/ascoli.png',
  bari: '../../../assets/logos/serieB/bari.png',
  brescia: '../../../assets/logos/serieB/brescia.png',
  catanzaro: '../../../assets/logos/serieB/catanzaro.png',
  cittadella: '../../../assets/logos/serieB/cittadella.png',
  como: '../../../assets/logos/serieB/como.png',
  cosenza: '../../../assets/logos/serieB/cosenza.png',
  cremonese: '../../../assets/logos/serieB/cremonese.png',
  feralpisalo: '../../../assets/logos/serieB/feralpisalo.png',
  lecco: '../../../assets/logos/serieB/lecco.png',
  modena: '../../../assets/logos/serieB/modena.png',
  palermo: '../../../assets/logos/serieB/palermo.png',
  parma: '../../../assets/logos/serieB/parma.png',
  pisa: '../../../assets/logos/serieB/pisa.png',
  reggiana: '../../../assets/logos/serieB/reggiana.png',
  sampdoria: '../../../assets/logos/serieB/sampdoria.png',
  spezia: '../../../assets/logos/serieB/spezia.png',
  sudtirol: '../../../assets/logos/serieB/sudtirol.png',
  ternana: '../../../assets/logos/serieB/ternana.png',
  venezia: '../../../assets/logos/serieB/venezia.png',
};

export const logosListPremierLeague: any = {
  logoPremierLeague: 'https://media.api-sports.io/football/leagues/39.png',
  arsenal: '../../../assets/logos/premierLeague/arsenal.png',
  aston_villa: '../../../assets/logos/premierLeague/aston villa.png',
  bournemouth: '../../../assets/logos/premierLeague/bournemouth.png',
  brighton: '../../../assets/logos/premierLeague/brighton.png',
  brentford: '../../../assets/logos/premierLeague/brentford.png',
  burnley: '../../../assets/logos/premierLeague/burnley.png',
  chelsea: '../../../assets/logos/premierLeague/chelsea.png',
  crystal_palace: '../../../assets/logos/premierLeague/crystal palace.png',
  everton: '../../../assets/logos/premierLeague/everton.png',
  fulham: '../../../assets/logos/premierLeague/fulham.png',
  liverpool: '../../../assets/logos/premierLeague/liverpool.png',
  luton: '../../../assets/logos/premierLeague/luton.png',
  manchester_city: '../../../assets/logos/premierLeague/manchester city.png',
  manchester_united:
    '../../../assets/logos/premierLeague/manchester united.png',
  newcastle: '../../../assets/logos/premierLeague/newcastle.png',
  nottingham_forest:
    '../../../assets/logos/premierLeague/nottingham forest.png',
  sheffield: '../../../assets/logos/premierLeague/sheffield.png',
  tottenham: '../../../assets/logos/premierLeague/tottenham.png',
  west_ham: '../../../assets/logos/premierLeague/west ham united.png',
  wolves: '../../../assets/logos/premierLeague/wolverhampton.png',
};
export const logosListChampionship: any = {
  logoChampionship: 'https://media.api-sports.io/football/leagues/39.png',
  birmingham: '../../../assets/logos/championship/birmingham.png',
  blackburn: '../../../assets/logos/championship/blackburn.png',
  bristol_city: '../../../assets/logos/championship/bristol city.png',
  cardiff: '../../../assets/logos/championship/cardiff.png',
  coventry: '../../../assets/logos/championship/coventry.png',
  huddersfield: '../../../assets/logos/championship/huddersfield.png',
  hull_city: '../../../assets/logos/championship/hull city.png',
  ipswich: '../../../assets/logos/championship/ipswich.png',
  leeds: '../../../assets/logos/championship/leeds.png',
  leicester: '../../../assets/logos/championship/leicester.png',
  middlesbrough: '../../../assets/logos/championship/middlesbrough.png',
  millwall: '../../../assets/logos/championship/millwall.png',
  norwich: '../../../assets/logos/championship/norwich.png',
  plymouth: '../../../assets/logos/championship/plymouth.png',
  preston: '../../../assets/logos/championship/preston.png',
  qpr: '../../../assets/logos/championship/qpr.png',
  rotherham: '../../../assets/logos/championship/rotherham.png',
  sheffield_wednesday:
    '../../../assets/logos/championship/sheffield wednesday.png',
  southampton: '../../../assets/logos/championship/southampton.png',
  stoke_city: '../../../assets/logos/championship/stoke city.png',
  sunderland: '../../../assets/logos/championship/sunderland.png',
  swansea: '../../../assets/logos/championship/swansea.png',
  watford: '../../../assets/logos/championship/watford.png',
  west_brom: '../../../assets/logos/championship/west brom.png',
};
